Refine the test which replay the error introduced in #1
In this test, the AttributeError will be raised:
AttributeError: 'tuple' object has no attribute 'split'